### ISSUE TITLE
Add autocomplete to bans

### ISSUE THREAD

**Issue by totallytavi** [FederationStudios/IRF_Administration#176]
Controversial idea because I know I'm going to get ratelimited, but consider checking the backend for a user's bans and then returning the valid games they're banned from.

Could be really simple, but it really depends on the right input in the username field so I don't spam Roblox a lot. Could do what Friz does and create a caching intermediary

**Comment by totallytavi** [comment]
Might start on this soon

**Comment by suman9725** [comment]
It may work.

**Comment by totallytavi** [comment]
The main that's needed here is a caching system to prevent spam on the Roblox API since their ratelimits are really harsh for non authenticated users.

**Comment by totallytavi** [comment]
Not presently working on it. I'll re-open if I find the time

**Comment by totallytavi** [comment]
I did not complete this Github, don't close it as that
